name: "info-action"
description: "GitHub Action for Getting information of repository."

outputs:
  owner:
    description: "Owner of repository"
    value: ${{ steps.info_repos.outputs.owner }}
  repository:
    description: "Repository name"
    value: ${{ steps.info_repos.outputs.repository }}
  version:
    description: "Version of repository"
    value: ${{ steps.info_repos.outputs.version }}
  version_hp:
    description: "Version(Hyphen) of repository"
    value: ${{ steps.info_repos.outputs.version_hp }}
  version_ub:
    description: "Version(Underbar) of repository"
    value: ${{ steps.info_repos.outputs.version_ub }}
  date:
    description: "Date of repository"
    value: ${{ steps.info_repos.outputs.date }}
  date1:
    description: "Date of repository"
    value: ${{ steps.info_repos.outputs.date1 }}
  release:
    description: "Name for release"
    value: ${{ steps.info_repos.outputs.release }}
  release_date:
    description: "Name for release with date"
    value: ${{ steps.info_repos.outputs.release_date }}

runs:
  using: "composite"
  steps:
    - shell: bash
      id: info_repos
      run: |
        OWNER=$(echo ${{ github.repository_owner }})
        REPOSITORY=$(echo ${{ github.repository }} | sed -e "s/$OWNER\///g")
        VERSION=$(echo ${{ github.ref }} | sed -e "s/refs\/tags\///g")
        VERSION_HP=$(echo ${VERSION} | sed -e "s/\./-/g")
        VERSION_UB=$(echo ${VERSION} | sed -e "s/\./_/g")
        DATE=$(TZ="Asia/Tokyo" date "+%Y%m%d%H%M%S")
        DATE1=$(TZ="Asia/Tokyo" date "+%Y/%m/%d (%a) %H:%M:%S")
        RELEASE="${REPOSITORY}_${VERSION_UB}"
        RELEASE_DATE="${REPOSITORY}_${DATE}"
        echo "::set-output name=owner::$OWNER"
        echo "::set-output name=repository::$REPOSITORY"
        echo "::set-output name=version::$VERSION"
        echo "::set-output name=version_hp::$VERSION_HP"
        echo "::set-output name=version_ub::$VERSION_UB"
        echo "::set-output name=date::$DATE"
        echo "::set-output name=date1::$DATE1"
        echo "::set-output name=release::$RELEASE"
        echo "::set-output name=release_date::$RELEASE_DATE"

